apiVersion: v1
kind: Service
metadata:
  name: boot-app
  namespace: skyq-jit
  labels:
    name: boot-app
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: boot-app
    territory: uk
    environment: test